import type { Metadata } from "next";
import "./globals.css";
import { RecurringPatternProvider } from "@/context/RecurringPatternContext";
import '../components/tests/MiniCalender.test';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <RecurringPatternProvider>
        {children}
      </RecurringPatternProvider>
    </body>
  </html>
  );
}
